<img src="http://www.numpy.org/_static/numpy_logo.png" width=600px>

# Criação de matrizes com o Numpy
#### [Voltar para a home.](index.html)

## Matrizes de uma dimensão

In [37]:
l1 = [-1,2,-3,4,-5] #Cria lista de python de uma dimensão
print ("Lista criada", l1) #Exibe a lista criada

Lista criada [-1, 2, -3, 4, -5]


In [46]:
import numpy as np #Importa a biblioteca numpy
a = np.array(l1) #Cria uma matriz apartir da lista "l1"
print("Matriz criada apartir da l1 utilizando o comando np.array")
print(a) #Exibe a matriz

Matriz criada apartir da l1 utilizando o comando np.array
[-1  2 -3  4 -5]


## Matrizes multidimensionais

In [27]:
l2 = [[1,2,3], [6,5,4]] #Cria uma lista de python de duas dimensões
print ("Lista criada",l2) #Exibe a lista

Lista criada [[1, 2, 3], [6, 5, 4]]


In [40]:
d = np.array(l2) #Cria uma matriz apartir da lista "l2"
print("Matriz criada apartir da l2 utilizando o comando np.array")
print(d) # Exibe a matriz

Matriz criada apartir da l2 utilizando o comando np.array
[[1 2 3]
 [6 5 4]]


In [26]:
matriz = np.arange(9).reshape(3,3) #Criando matriz com numeros de zero a nove e dimensões 3 x 3
print(matriz)
 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### [Voltar para a home.](index.html)