# Numpy
#### [Voltar para a home.](index.html)
## Manipulação e operações com matrizes

### Criando matriz 4 x 4

In [98]:
import numpy as np # Importa a biblioteca numpy
matriz = np.arange(16).reshape(4,4)   #Criando matriz 4 x 4
print(matriz)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Exibindo um elemento da matriz "o numero 6"

In [41]:
matriz[1, 2] # Exibe o elemento da linha 1 culuna 2 "lembrando que a contagem das linhas e das colunas começam do "0"

6

### Multiplicação cada elemento da matriz  por 2

In [47]:
matrizb = matriz*2 # Exibe o produto de cada elemento da matriz por 2
matrizb

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

### Nova matriz rotacionando a anterior

In [99]:
matrizc = np.transpose(matrizb) # Criação de uma nova matriz rotacionando a anterior
matrizc

array([[ 0,  8, 16, 24],
       [ 2, 10, 18, 26],
       [ 4, 12, 20, 28],
       [ 6, 14, 22, 30]])

### Soma entre os elementos das matrizes

In [100]:
matrizb + matrizc

array([[ 0, 10, 20, 30],
       [10, 20, 30, 40],
       [20, 30, 40, 50],
       [30, 40, 50, 60]])

### Subtração entre os elementos das matrizes

In [101]:
matrizb - matrizc

array([[  0,  -6, -12, -18],
       [  6,   0,  -6, -12],
       [ 12,   6,   0,  -6],
       [ 18,  12,   6,   0]])

### Produto de matrizes

Para realizar o produto de matrizes utilizamos o método np.dot

In [102]:
np.dot(matrizb, matrizc) # Produdo de matrizes utilizando o np.dot

array([[  56,  152,  248,  344],
       [ 152,  504,  856, 1208],
       [ 248,  856, 1464, 2072],
       [ 344, 1208, 2072, 2936]])

#### [Voltar para a home.](index.html)