<img src="http://www.numpy.org/_static/numpy_logo.png" width=400px>

In [21]:
import numpy as np #importa a biblioteca numpy 

## Diferenças dos arrays do numpy para as listas de python

In [23]:
lista = [1,2,3,4,5] #lista de python
lista*2 #lista duas vezes

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [4]:
array = np.array([lista]) #array do numpy
print(array*2) #produto de cada elemento por 2

[[ 2  4  6  8 10]]


**de modo que podemos fazer operações em lote com maior facilidade:**

ex.: aplicando a seguinte função a todos os elementos do array:

$f(x) = \frac{x^2}{2x}$ 

In [43]:
#código da função acima
def f(x): 
    return x**2/2*x

In [42]:
f(array)

array([[  0.5,   4. ,  13.5,  32. ,  62.5]])

## arrays multidimensionais

In [26]:
matriz = np.arange(9).reshape(3,3)   #Criando matriz 3 x 3
print(matriz)
 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Indices

<img src="cap2.png" width=100px>

In [39]:
matriz[1, 2] #exibe o elemento da linha 1 culuna 2 "lembrando que indices começam do 0"

5

### Operações com matrizes:

In [29]:
matrizB = np.transpose(matriz) #criação de uma nova matriz rotacionando a anterior
matrizB

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [35]:
matriz + matrizB #soma entre os elementos das matrizes

array([[ 0,  4,  8],
       [ 4,  8, 12],
       [ 8, 12, 16]])

In [36]:
matriz - matrizB #subtração entre os elementos das matrizes

array([[ 0, -2, -4],
       [ 2,  0, -2],
       [ 4,  2,  0]])

In [31]:
matrizB * matriz # produto entre os elementos das matrizes

array([[ 0,  3, 12],
       [ 3, 16, 35],
       [12, 35, 64]])

In [33]:
matrizB @ matriz # multiplicação de matrizes

array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])

In [34]:
np.dot(matrizB, matriz) # multiplicação de matrizes

array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])